services:
  event_sql:
    image: mysql
    ports:
      - 3309:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./event_sql/:/docker-entrypoint-initdb.d
    networks:
      - EventNet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 1s
      retries: 10
  event_cons:
    build: ./event_cons
    image: event_cons
    ports:
      - 8087:8080
    volumes:
      - ./event_cons:/event_cons
    networks:
      - EONet
      - EventNet
    depends_on:
      event_sql:
        condition: service_healthy
      event_svc:
        condition: service_started
  event_svc:
    build: ./event_svc
    image: event_svc
    ports:
      - 8086:8080
    volumes:
      - ./event_svc:/event_svc
    networks:
      - EONet
      - EventNet
    depends_on:
      event_sql:
        condition: service_healthy
networks:
  EONet:
    external: true
  EventNet:
