services:
  order_sql:
    image: mysql
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./order_sql/:/docker-entrypoint-initdb.d
    networks:
      - OrderNet
  order_cons:
    build: ./order_cons
    image: order_cons
    ports:
      - 8085:8085
    volumes:
      - ./order_cons:/order_cons
    networks:
      - EONet
      - OrderNet
    depends_on:
      order_sql:
        condition: service_started
      order_svc:
        condition: service_started
  order_svc:
    build: ./order_svc
    image: order_svc
    ports:
      - 8084:8084
    volumes:
      - ./order_svc:/order_svc
    networks:
      - EONet
      - OrderNet
    depends_on:
      order_sql:
        condition: service_started
networks:
  EONet:
    external: true
  OrderNet: