services:
  order_sql:
    image: mysql
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./order_sql/:/docker-entrypoint-initdb.d
    networks:
      - OrderNet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 1s
      retries: 10
  order_cons:
    build: ./order_cons
    image: order_cons
    ports:
      - 8085:8080
    volumes:
      - ./order_cons:/order_cons
    networks:
      - EONet
      - OrderNet
    depends_on:
      order_sql:
        condition: service_healthy
      order_svc:
        condition: service_started
  order_svc:
    build: ./order_svc
    image: order_svc
    ports:
      - 8084:8080
    volumes:
      - ./order_svc:/order_svc
    networks:
      - EONet
      - OrderNet
    depends_on:
      order_sql:
        condition: service_healthy
networks:
  EONet:
    external: true
  OrderNet:
