services:
  staff_sql:
    image: mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./staff_sql/:/docker-entrypoint-initdb.d
    networks:
      - StaffNet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 1s
      retries: 10
  staff_cons:
    build: ./staff_cons
    image: staff_cons
    ports:
      - 8083:8080
    volumes:
      - ./staff_cons:/staff_cons
    networks:
      - EONet
      - StaffNet
    depends_on:
      staff_sql:
        condition: service_healthy
      staff_svc:
        condition: service_started
  staff_svc:
    build: ./staff_svc
    image: staff_svc
    ports:
      - 8082:8080
    volumes:
      - ./staff_svc:/staff_svc
    networks:
      - EONet
      - StaffNet
    depends_on:
      staff_sql:
        condition: service_healthy
networks:
  EONet:
    external: true
  StaffNet:
